### ISSUE TITLE
PlayerVaults wont store Crate Keys.

### ISSUE THREAD

**Issue by ScoutGod** [drtshock/PlayerVaults#104]
Hello, I am using the latest version of ArchonCrates and PlayerVaults. For some reason when my donors store crate keys, they disappear after some time.. Whats up? Would appreciate the help, also just a side note: crate keys do store in enderchests just fine.

**Comment by drtshock** [comment]
Which version of playervaults and which version of spigot? Also, can you link to the crate plugin so I can see how they are created please.

**Comment by ScoutGod** [comment]
I am using the latest stable version of Spigot which is 1.8.8
I am also using the latest version of PlayerVaults.

ArchonCrates: http://dev.bukkit.org/bukkit-plugins/archoncrates/

**Comment by drtshock** [comment]
Version number for playervaults please?

**Comment by ScoutGod** [comment]
3.5.6

**Comment by drtshock** [comment]
What breaks when you do it? Does it lose its glow?

**Comment by ScoutGod** [comment]
It completely disappears.

**Comment by drtshock** [comment]
What disappears? The lore, the item meta, the actual item?

**Comment by ScoutGod** [comment]
The actual item.

**Comment by drtshock** [comment]
so you put it in there, close your vault, then reopen it and it's gone right away?

**Comment by ScoutGod** [comment]
It usually happens after the server has its daily restarts. Or after a reload.

**Comment by ScoutGod** [comment]
It stores everything that it had that's not a key, but deletes the key. I wonder if its because of a custom name, or lore?

**Comment by drtshock** [comment]
Do this for me please:

Start the server
Put a key in your vault
Save a copy of the vault file in a gist https://gist.github.com
Stop the server, save another copy in a gist.
Start the server, save another copy.
Reopen the vault, see if it's still there, then save a final copy.

Send me all of those and we'll see where the issue is. I'd also like a screenshot of the key as I didn't see anything unusual in the archonkey's code that would lead me to believe we'd lose any data for it.

**Comment by kashike** [comment]
If this is still an issue with the most recent version, please open a new issue.
