### ISSUE TITLE
Playervaults "Hide Attributes Flag"

### ISSUE THREAD

**Issue by BiGUNMAN** [drtshock/PlayerVaults#208]
I reported this on the SpigotMC forums and it seems to have been dismissed, so here's the issue I reported there: I put an item with a  Hide Attributes flag in a vault (item had the maxhealth attribute and hide attributes flag). When I opened up the vault again all the data on the item is lost, the lore, name, attributes. Here's the error: http://pastebin.com/RcdfM4JK

**Comment by drtshock** [comment]
Things are only serialized if bukkit knows about it. It doesn't know about the flags unfortunately so it losses everything :c

**Comment by drtshock** [comment]
Though pretty sure we have something that should safely catch this now if you updated to a build from ci.drtshock.net

**Comment by BiGUNMAN** [comment]
@drtshock Unfortunately this is not the case, just tested it out: http://pastebin.com/8zzxF8mw
Version: http://imgur.com/a/z6CmV

**Comment by mumbai52** [comment]
Yes, please fix this bug as I have a custom plugin on my server which hides enchants on all enchanted items, because of this bug, every time someone puts an enchanted item into their playervault, they lose all of the enchants on it, please fix this as soon as possible, this problem was not present in the older versions of playervault.

**Comment by tuanjr** [comment]
Please fix it, many many plugin can't use.

**Comment by kashike** [comment]
https://github.com/drtshock/PlayerVaults/pull/220
