### ISSUE TITLE
Items Removed

### ISSUE THREAD

**Issue by NathanWolfu** [drtshock/PlayerVaults#239]
Items periodically get removed from players vaults.

**Comment by SmellyGeek** [comment]
This isn't elaborate. Can you provide more information on the issue? Such as

- When this happens, is there an internal error or stacktrace in console?
- Are these vanilla items being removed? If they are, any unsafe enchantments?
- Can you leave an ip address to your server so that we may login and try to replicate this issue?

**Comment by camdenorrb** [comment]
Same thing occurred to me.
