### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by HelixCarter** [drtshock/PlayerVaults#261]
So I Can Open Vaults So Can My Staff But The Players Can't
I Says They Do Not Have Permission Can You Please Fix This Also Heres My Ranks Config:

  Warrior:
    default: false
    permission: 
    - +playervaults.commands.use
    - playervaults.signs.bypass
    - +playervaults.ammount.2
    inheritance:
    - member
    info:
      prefix: '&7&lWarrior &f'
      build: true
      suffix: '&f'
  Gladiator:
    default: false
    permission: 
    - playervaults.commands.use
    - +playervaults.amount.4
    inheritance:
    - warrior
    info:
      prefix: '&f&lGladiator &6'
      build: true
      suffix: ''
  Wizard:
    default: false
    permission: 
    - playervaults.commands.use
    - playervaults.amount.6
    - shop.vip.vip1
    - essentials.nick
    inheritance:
    - gladiator
    info:
      prefix: '&b&lWizard &6'
      build: true
      suffix: ''
  BETA:
    default: false
    permission: []
    inheritance:
    - wizard
    info:
      prefix: '&e&lBETA &6'
      build: true
      suffix: ''
  Genesis:
    default: false
    permission: 
    - playervaults.commands.use    
    - playervaults.amount.8
    inheritance:
    - wizard
    info:
      prefix: '&a&lGenesis &6'
      build: true
      suffix: ''

Is There Anything Wrong With It

- Helix

**Comment by fordross** [comment]
At a glance, Warrirors have +playervaults.ammount.2.  'amount' is misspelled there, and the node should not have a + sign at the front of it.

Gladiators have +playervaults.amount.4 and the node should not have a + sign at the front of it.

If Wizards cannot use the commands, it is not immediately apparent to me why - the permissions you pasted do not include correct indentation, so if you are using any tabs instead of whitespaces, you can expect it to fail (or the wrong number of whitespaces, etc).
