### ISSUE TITLE
Player can't access their pv after putting in maps

### ISSUE THREAD

**Issue by Managering** [drtshock/PlayerVaults#266]
Player says he added maps into his player vault, after doing so, couldn't re-open their vault, 'internal error'
error is: https://hastebin.com/ulolevuniv.vbs

Please advice.

**Comment by virustotalop** [comment]
Take a look at the uuidvaults directory in PlayerVaults and find the vault of the player, you can look up the uuid of the player on [namemc](https://namemc.com). It seems like this bug is caused by non-ascii characters in display names at least in my case. For example on my server this is the data that was stored.
`!!binary|-eyI9PSI6Im9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFjayIsInR5cGUiOiJESUFNT05EX1BJQ0tBWEUiLCJtZXRhIjp7Ij09IjoiSXRlbU1ldGEiLCJtZXRhLXR5cGUiOiJVTlNQRUNJRklDIiwiZW5jaGFudHMiOnsiRFVSQUJJTElUWSI6MTgwLCJESUdfU1BFRUQiOjE4MCwiTE9PVF9CT05VU19CTE9DS1MiOjIwMH0sImludGVybmFsIjoiSDRzSUFBQUFBQUFBQUJXTVFRckNNQlFGbjBaQnF0SXpDRzREcWNaaTlycHo0UlhTOU1jRzA3U1F0dFRibTY3ZU1BTXZBekxrajFcL1FyVFBQWUJvZGhzaHdwTG4zWFhSZE1HTkZBSEtHZlhDZlpwamNZcE5aTVd3YkhZZWxzc1N4SjZvVHI5UGg0ZTNNVjhcLzBvb2w4YW41WnRLZGloODA0dWhwbmFWVmh6ZTNLZFVtU1M2V0lheEozYnEwcWhhbUlCRjJBUDZmTVIwS2VBQUFBIiwibG9yZSI6WyLCpzjCp20tLS0tLS0tLS0tLS0tLS0tLS0iLCLCp2VHb2QgcGlja2F4ZSIsIsKnZWZyb20gdGhlIGtpdCIsIsKnNyIsIsKnN1Jhcml0eTrCp2VSYW5rIEV4Y2x1c2l2ZSIsIsKnNyIsIsKnOMKnbS0tLS0tLS0tLS0tLS0tLS0tLSJdLCJkaXNwbGF5LW5hbWUiOiLiiaTOqeKJpfCdkI/wnZCo8J2QrfCdkJrik4Xik57ik6Pik5Dik6Pik57iiaTOqeKJpeKEoiIsInJlcGFpci1jb3N0Ijo3fX0=`

When converted from base64 it spits out
`{"==":"org.bukkit.inventory.ItemStack","type":"DIAMOND_PICKAXE","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"DURABILITY":180,"DIG_SPEED":180,"LOOT_BONUS_BLOCKS":200},"internal":"H4sIAAAAAAAAABWMQQrCMBQFn0ZBqtIzCG4DqcZi9rpz4RXS9McG07SQttTbm67eMAMvAzLkj1\/QrTPPYBodhshwpLn3XXRdMGNFAHKGfXCfZpjcYpNZMWwbHYelssSxJ6oTr9Ph4e3MV8\/0ool8an5ZtKdih804uhpnaVVhze3KdUmSS6WIaxJ3bq0qhamIBF2AP6fMR0KeAAAA","lore":["§8§m------------------","§eGod pickaxe","§efrom the kit","§7","§7Rarity:§eRank Exclusive","§7","§8§m------------------"],"display-name":"≤Ω≥𝐏𝐨𝐭𝐚Ⓟⓞⓣⓐⓣⓞ≤Ω≥™","repair-cost":7}}`

Hope that helps.

**Comment by Managering** [comment]
Oh wow I never replied to this I see, I'm sorry.

I did find the cause after you're help. Thank you, ticket may be closed.
