### ISSUE TITLE
Bug PlayerVaults 2017

### ISSUE THREAD

**Issue by MrXmarks** [drtshock/PlayerVaults#268]
Hello, i found bug playervaults.
Playervaults inventory between me and players it so different.
When i try to take out items from pv player, but its nothing.

![2017-06-02_02 13 53](https://cloud.githubusercontent.com/assets/25476996/26696665/8f010d08-4739-11e7-8035-4393ddb92ff6.png)
![2017-06-02_02 14 17](https://cloud.githubusercontent.com/assets/25476996/26696666/8f02dfe8-4739-11e7-9d81-b003b79b7bd2.png)

**Comment by Faxed** [comment]
This is an issue which was open since late 2016, I believe - Until another user came along and wiped every issue off the board. 

If you check the PlayerVaults folder, whilst the plugin will load the UUID vault for the player who does "/pv 1" (or whatever), if you try to open it as an admin it'll open (and save) the vault under the player's name - So it won't affect the player's overall vault, as the UUID file is the one loaded and saved by the player's use of the commands.
