### ISSUE TITLE
Big issue: Error when migration from PlayerVault to PlayerVaultX

### ISSUE THREAD

**Issue by LapizSeller** [drtshock/PlayerVaults#323]
i found big issue when tried to migration from PlayerVault to PlayerVaultX. if uuidvaults has playervault corrupt (vault can't open) so migration progess is corrupt (discontinous) when it meet corrupted vault.
As you can see, number of files within uuidvault folder vs number of files  base64vaults folder:

http://i.imgur.com/Bo4Fqki.jpg
![alt text](http://i.imgur.com/Bo4Fqki.jpg)

This is error when migration: https://paste.ubuntu.com/26366849/
Convert from PlayerVault build 209 to PlayervaultX latest version
PaperSpigot 1.11.2

**Comment by drtshock** [comment]
https://github.com/drtshock/PlayerVaults/commit/d3cb9d458aa6eff726c02af4fc4a56b6c342cbc8

If you can join discord, I'll send you the version with that commit. Or you can compile it yourself if you know how. 

What it does is just catch any errors on conversion of a single vault and if it finds one, it logs it and then moves on instead of exiting the conversion method like it did for you. It'll also spit out how many fail at the end in its log message of the conversion summary.
