### ISSUE TITLE
Items with names starting with &0 (black color code) lose their color if stored in a vault

### ISSUE THREAD

**Issue by Momshroom** [drtshock/PlayerVaults#398]
### PlayerVaultsX Version
*Run `/version playervaults` and give us your output.* 
[00:31:49 INFO]: PlayerVaults version 4.1.4
[00:31:49 INFO]: Website: https://www.spigotmc.org/resources/51204/
[00:31:49 INFO]: Authors: drtshock and kashike

### Server Version
*Run `/version` and give us your output.*
[00:32:12 INFO]: This server is running Paper version git-Paper-192 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[00:32:12 INFO]: Checking version, please wait...
[00:32:13 INFO]: Previous version: git-Paper-176 (MC: 1.14.4)
[00:32:13 INFO]: You are 17 version(s) behind

### Logs
*Give use your logs by going to `logs/latest.log`.*
https://gist.github.com/Momshroom/99bbc2d8a5e787d064a4144ac71f0440

### Details
*Please explain the problem.*
Named items with the &0 color code at the beginning lose their color when stored in a player vault.  All other color codes seem to work fine.. it's just black names.

ie: I name a pick &0pick.  The name appears black.  I put it in my player vault, close the vault and re-open.  The name is now just 'pick' and no longer black.

**Comment by drtshock** [comment]
That's interesting. Thanks, I'll look into it.

**Comment by Ichbinjoe** [comment]
Issue confirmed - Immediate suspicion is that this is instead a bug with Spigot & co

**Comment by Ichbinjoe** [comment]
This is an issue in Spigot - probably from all of time. I PR'd a 1.14 fix.

**Comment by Ichbinjoe** [comment]
Paper doesn't want the fix just in Paper - I have no interest in pursuing the fix in CB/Spigot, but I left the diff if you wanna go complain to md__5.

**Comment by Sycholic** [comment]
prob because black is a invalid color you cant have black on black?... try testing it as a combo different BG color.  also Ichbinjoe you need to stop drop bs accusations @ spigot when you know full well it cuz its craftbukkit its been there known long forgotten issue. also dont care if you have personal issues with md_5 dont be pulling down a whole team because your personal issues.  keep it to yourself.

**Comment by Ichbinjoe** [comment]
@Sycholic you are more than welcome to take my patch and submit it yourself.

**Comment by Ichbinjoe** [comment]
As a workaround (unless this is something user created) you can use &r&0 and it will maintain the coloring.

**Comment by Sycholic** [comment]
just saying shouldnt be trashing people in issues.  drop the patch somewhere I will actually look at it. but I think its actually intended to not be allowed to avoid possible exploiting?

**Comment by Ichbinjoe** [comment]
@Sycholic If you looked at the PR you probably came from, you would see the patch, as well as my explanation on why it is a problem and how I fixed it.

Quite frankly, all I see is you attacking me and calling me names in IRC. Please respect that all of my Minecraft work is 100% volunteer and I do this for the love of the Minecraft open source community.

I don't understand your 'avoid possible exploiting'. How would a player exploit this? By making sections of the name black? If you were to look at the patch I think its fairly clear that this wasn't the intended behavior and instead due to a mistake in allowing a default be used in too many situations.

**Comment by Sycholic** [comment]
you closed the other issue so I was reading more to see what was going on specifically and for what.  btw this issue been around since like 2011/2012 its not something new, cb/bukkit didnt fix it back then there a reason it wasnt fixed still... since you cant determine if a client has any kind of alpha on their text bg, allowing black on black is just asking for it.  and Im not the only person who thinks it as well.. so patch it yourself.  and to if you take offense for me calling you anything oh well. maybe you shouldnt throw rocks in glass houses?  Im done, I was gonna take a serious look but now ya playing the victim?... yeah Im out GL with the complaints you inviting to get.

**Comment by Sycholic** [comment]
Sorry Drshock I cleaned up after myself.  so I'll just comment to you 'its likely intended' there is a work around. but I think you asking for complaints from the user base once you start putting black FG on a black BG. because there is no way to determine if a user has a transparent BG or not.

**Comment by CmdrKittens** [comment]
With this being an issue outside this plugin, I am for now closing this.
