### ISSUE TITLE
Viewing offline player's vaults?

### ISSUE THREAD

**Issue by Theepwner** [drtshock/PlayerVaults#64]
Trying to view an offline player's vaults:
http://hastebin.com/jumozugufu.profile

Is this just not supported?

**Comment by johandrex** [comment]
He told me to raise the cache but it's still not working

**Comment by drtshock** [comment]
The issue with offline player vaults is that it it won't know the size the vault should be when it's opened so it'll show to you as a double chest. The error you see there is because I missed a null check and tried to check a permission on an offline player.

Offline player's vaults can be viewed. The way it works is it'll try to find an offline player object for the name you provide. If that is found (in the spigot cache), then it'll grab the UUID (from the cache) and open the file for that UUID. If it can't find that name or uuid in the cache, then it will tell you that it doesn't exist even though it might.

The only way around the above is to do a UUID fetching service which I don't want to do. I will push a fix for the NPE issue in a second though.
