### ISSUE TITLE
PlayerVaults Constantly reseting

### ISSUE THREAD

**Issue by BTTP** [drtshock/PlayerVaults#77]
I dont know why but at random times for unknown reasons players log on and there player vaults r wiped

**Comment by kashike** [comment]
Please provide more information when opening an issue.

 - What version of PlayerVaults are you running?
 - Does your server log contain any stacktraces/exceptions?

**Comment by BTTP** [comment]
I'm using the latest version and I don't see any exceptions I have watched the console and triple checked logs. People just log in and there PVs r empty or deleted

**Comment by mibby** [comment]
Could it be related to the caching?
https://github.com/drtshock/PlayerVaults/commit/9cd5755d0abdf1cc749a270800254d84af8dcf87

Try downgrading to build 170. http://ci.drtshock.net/job/PlayerVaults/170/

**Comment by drtshock** [comment]
Let me know if downgrading helps.

**Comment by mibby** [comment]
Since downgrading to dev build 169, I haven't had any more reports of player vaults duping items or not saving. So upon my experience, I think something may be wrong with how it caches - not saving the latest inventory state. Caching also seemed to crash my server upon flushing to file, per another ticket I submitted, which downgrading seemed to have resolved.

**Comment by drtshock** [comment]
Just ftr, referring to https://github.com/drtshock/PlayerVaults/commit/9cd5755d0abdf1cc749a270800254d84af8dcf87

**Comment by drtshock** [comment]
Should be fixed here https://github.com/drtshock/PlayerVaults/compare/c2fa317e169c...a5ed2b1f4dc2
